# Generated by Django 3.2.9 on 2022-05-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0005_remove_complaint_request_request_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint_request',
            old_name='complaint',
            new_name='requested_complaint',
        ),
    ]
