# Generated by Django 3.2.9 on 2022-02-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaint_complaint_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_upvotes_users',
            field=models.JSONField(default=None),
        ),
    ]
