# Generated by Django 3.2.9 on 2022-03-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0017_complaint_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_abc',
            field=models.JSONField(null=True),
        ),
    ]
