# Generated by Django 3.2.9 on 2022-03-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0020_rename_complaint_abc_complaint_complaint_place_geocoder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_place_geocoder',
            new_name='complaint_place_geocode',
        ),
    ]
