# Generated by Django 3.2.9 on 2022-05-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0022_alter_complaint_complaint_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=1000, null=True)),
                ('tag_complaints', models.JSONField(null=True)),
            ],
        ),
    ]
