# Generated by Django 3.2.9 on 2022-05-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0004_remove_contact_request_request_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_request',
            name='request_note',
        ),
    ]
