# Generated by Django 3.2.9 on 2022-05-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0007_auto_20220521_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_request',
            name='request_read',
        ),
        migrations.RemoveField(
            model_name='contact_request',
            name='request_read',
        ),
    ]
