# Generated by Django 3.2.9 on 2022-05-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_user_user_complaints_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_session_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
