# Generated by Django 3.2.9 on 2022-02-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_user_document_user_file_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_ratings_figure',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_ratings_total',
            field=models.IntegerField(default=0),
        ),
    ]
