# Generated by Django 3.2.9 on 2022-02-16 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20220216_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_ratings_figure',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_ratings_total',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_score', models.FloatField(default=0.0)),
                ('rating_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_from', to=settings.AUTH_USER_MODEL)),
                ('rating_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
