# Generated by Django 3.2.9 on 2022-03-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_user_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_place',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_place_geocode',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
