# Generated by Django 3.2.9 on 2022-03-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_remove_user_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_complaints_solved',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
