# Generated by Django 3.2.9 on 2022-02-20 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_complaint_complaint_downvotes_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_file', models.ImageField(null=True, upload_to='identity')),
                ('complaint_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_documents', to='complaints.complaint')),
            ],
        ),
    ]
