# Generated by Django 3.2.9 on 2022-03-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0019_alter_complaint_complaint_abc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_abc',
            new_name='complaint_place_geocoder',
        ),
    ]
