# Generated by Django 3.2.9 on 2022-03-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0021_rename_complaint_place_geocoder_complaint_complaint_place_geocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_place',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
